### ISSUE TITLE
Integration with Movecraft

### ISSUE THREAD

**Issue by TylerS1066** [pmdevita/CreeperHeal2#17]
Rather than continue in #16 , I figured it'd be best if we discuss how we want to integrate these two plugins here in an issue (since I agree that the implementation in that PR is a bit of a quick fix).

One major issue we had previously with Movecraft 6 was that it was almost impossible to get developers setup and compiling it since we had 10+ dependencies, and chances were that at any one moment one of their maven repositories would be down (or changed).  As such, a large change we did when moving to Movecraft 7 (and now 8) is to make add-on plugins (e.g. [Movecraft-CoreProtect](https://github.com/APDevTeam/Movecraft-CoreProtect)) and thin down our core plugin to zero external dependencies.  Not only has this allowed us to be very quick at updating the core plugin to new Minecraft versions, it's also allowed us to clean up each code base individually and more cleanly define each functionality.  That said, I'd rather not add another add-on to the 8+ we already maintain, so if you feel comfortable with it we can easily add an integration to this plugin to check the hitbox of a craft against explosions.

As to implementation of that, there's a few useful things to know.  First up, the `CraftManager` has a `.getInstance()` static method to grab a reference to it, and from there you can do `.getCraftsInWorld(World)` to get all the crafts in the world, and you can use `.getHitBox()` to get their hitbox.  Once you have the crafts (or their hitboxes), we have a `MathUtils` class with the `locationNearHitBox(HitBox, Location, distance)` static function which is optimized to quickly rule out if a location is near a hitbox.  I'd probably suggest taking the list of crafts, seeing if the explosion is within say, 100 blocks of the origin, then for each block in the explosion list check if it is in the hitbox of any of the crafts (using `.contains(x, y, z)`, and if so don't heal it.

I'm a bit busy for the next few days updating our servers and polishing off our plugins for another round of alpha releases, but I can probably circle back around to this later in the week if you don't want to take a stab at it.

**Comment by pmdevita** [comment]
Yes, I think it would be fine to add this to the plugin directly for now. If other integrations get put together down the line, maybe I'll move each of them out to their own add-on plugins.
I think that gives me a pretty good idea of what to go on for implementation too. Is it additionally possible to get which blocks are in the craft? It should be possible to be able to mask out those blocks specifically, so if the craft is near something the explosion properly affects the nearby blocks.

**Comment by TylerS1066** [comment]
Our `HitBox` interface extends `Iterable<MovecraftLocation>` and also implements very fast operations for `contains(int x, int y, int z)`, which should be all you need to check if a block is in the `HitBox` of the craft (all blocks moved with them) or mask them out of explosions.  `MovecraftLocation`s are just compact representations of the integer vector <x, y, z> which are efficiently packed/unpacked into a long and hashed for internal usage.  Our `MathUtils` class contains a function to convert a `org.bukkit.Location` into a `MovecraftLocation`, and `MovecraftLocation` includes a handy function to convert it to a `org.bukkit.Location`, which you could then get the block by using the `getBlock()` function, but I think that it'd be most efficient to deal only in locations.

**Comment by pmdevita** [comment]
Ah, I think I got mixed up thinking that they were just hull hit boxes. That should be pretty easy to make this work then.

**Comment by pmdevita** [comment]
OK it should work now, here's the jar since something is wrong with the GitHub action (I'm getting some error about `Unresolved reference: LinkedList` which might indicate something wrong with the Kotlin stdlib but it compiles fine on my machine). Let me know if you think this is working correctly.

Also, do you know anything about Java ServiceProviders? I tried implementing the compatibility system as one and I can neither get AutoService to properly annotate or for it load even when manually writing the service definition.

**Comment by TylerS1066** [comment]
I do not know anything about Java ServiceProviders.

I tried out the jar, and something you changed seems to have broken compatibility with 1.14.4 (yes I know we're a few years out of date, we're working on it):
```
[20:41:51] [Server thread/ERROR]: Could not load 'plugins/CreeperHeal2-1.5.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchFieldError: CRIMSON_FUNGUS
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.14.4.jar:git-Paper-"a168ecf0"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.4.jar:git-Paper-"a168ecf0"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.4.jar:git-Paper-"a168ecf0"]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-"a168ecf0"]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-"a168ecf0"]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-"a168ecf0"]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.NoSuchFieldError: CRIMSON_FUNGUS
	at net.pdevita.creeperheal2.constants.Blocks16.<clinit>(DependentBlocks.kt:291) ~[?:?]
	at net.pdevita.creeperheal2.constants.DependentBlocksKt.<clinit>(DependentBlocks.kt:45) ~[?:?]
	at net.pdevita.creeperheal2.constants.DependentBlocks.<init>(DependentBlocks.kt:15) ~[?:?]
	at net.pdevita.creeperheal2.constants.ConstantsManager.<init>(ConstantsManager.kt:11) ~[?:?]
	at net.pdevita.creeperheal2.CreeperHeal2.<init>(CreeperHeal2.kt:18) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404) ~[?:?]
	at java.lang.Class.newInstance(Class.java:591) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:75) ~[patched_1.14.4.jar:git-Paper-"a168ecf0"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-"a168ecf0"]
	... 6 more
```

I think that the `VERSION_TO_BLOCKS` array in `DepedendentBlocks.kt` is being built on startup, causing it to try and load all of them, of which `Blocks16` and `CRIMSON_FUNGUS` are the first to error.

**Comment by pmdevita** [comment]
OK this should all work now, let me know if it seems correct! You might want to enable debug mode since there is some output about the compatibility module https://github.com/pmdevita/CreeperHeal2/actions/runs/3803386811 d

**Comment by TylerS1066** [comment]
> [15:14:25] [Server thread/INFO]: [CreeperHeal2] Enabling CreeperHeal2 v1.5.0
> [15:14:25] [Server thread/INFO]: [CreeperHeal2] Found 1 compatibility plugin(s)
> [15:14:25] [Server thread/INFO]: [CreeperHeal2] Loading compatibility for plugin Movecraft
> [...}
> [15:17:29] [Server thread/INFO]: Masked out 0 blocks from the explosion

I'm not sure what is wrong, it seems to have loaded the Movecraft integration but not be masking any blocks out.

**Comment by pmdevita** [comment]
Weird, was this with the 8.0.0 beta?

**Comment by TylerS1066** [comment]
This is with 8.0.0_beta-1.  That looks right to me, but I never saw the message about finding a craft near the explosion.  I know that 50 might be a bit low of an estimate (I've seen crafts nearing 150 blocks on our servers, and I'm sure other people are making much larger crafts), but I was testing right on top of the center of my craft.

**Comment by pmdevita** [comment]
Was the craft piloted at the time?

**Comment by TylerS1066** [comment]
Yes it was.

**Comment by pmdevita** [comment]
Hmm try the most recent build here instead? https://github.com/pmdevita/CreeperHeal2/actions/runs/3805329214 I'm running out of ideas, I can try and make a build with more debug printing next

**Comment by pmdevita** [comment]
Actually use this one https://github.com/pmdevita/CreeperHeal2/actions/runs/3809431709 this adds more debugging

**Comment by TylerS1066** [comment]
Ok here's what I got, and I think it's showing a problem:
> [10:53:39] [Server thread/INFO]: Explosion strength: 2.0 at 7169.0,76.0,6355.0
> [10:53:39] [Server thread/INFO]: [CreeperHeal2] Checking Movecraft for explosion at Location{world=CraftWorld{name=world},x=10754.5,y=115.0,z=9533.0,pitch=0.0,yaw=0.0}
> [10:53:39] [Server thread/INFO]: [CreeperHeal2] Checking against craft  at (7172,76,6355)
> [10:53:39] [Server thread/INFO]: [CreeperHeal2] Masked out 0 blocks from the explosion

The first message seems to be a bit off on the location of the explosion (I placed the TNT at `<7173,90,6352>`), but that might be the bottom-left hand corner of the explosion area.  The second message has a completely different center value in a very far away part of the world, which seems to be eliminating it from being considered (>50 blocks away).

After looking into the code a bit, I'm pretty sure the first debug message is from a different plugin on our testing server (most likely one of our protection plugins).  I think the problem here is probably something in the `Boundary` class messing up the center, causing us to eliminate the craft because it's too far away?

**Comment by pmdevita** [comment]
Oh yep, I somehow forgot order of operations while writing the center calculation. I must never have noticed this because I was testing very close to the world origin. Try this https://github.com/pmdevita/CreeperHeal2/actions/runs/3813346883

**Comment by TylerS1066** [comment]
It worked!  I tested with a few different crafts and didn't have any problems with them regenning even on crafts over 200 blocks long.

**Comment by pmdevita** [comment]
Fantastic! I'll mark this closed then.
