### ISSUE TITLE
Add additional explosion repair customizations

### ISSUE THREAD

**Issue by pmdevita** [pmdevita/CreeperHeal2#29]
Options should be added and implemented for the following features

- Allow disabling of saving container contents in an explosion
- Allow specifications of a list of block types (MATERIAL enum types) to not save

**Comment by TylorTurner** [comment]
Allow specifications of a list of block types (MATERIAL enum types) to not save

Does that mean disabled regenning certain block types? That would be excellent! When do you think this would be done. I can test it if you need me to.

**Comment by TylorTurner** [comment]
yeah, I sent you the videos in Discord that something was wrong. I can send you updated videos tomorrow morning.

**Comment by pmdevita** [comment]
Resolved with 96c442c
