### ISSUE TITLE
account for falling blocks

### ISSUE THREAD

**Issue by xsmeths** [pmdevita/CreeperHeal2#3]
when a chain of explosions is made in a desert and some of the sand falls it doesn't fix it leaving holes in the map in those areas
can provide any other information you need, just reply and ask :)

spigot 1.16.4
crepeprheal2-1.1.0

**Comment by pmdevita** [comment]
Can you send a screenshot of what it looks like and what you expected it to look like? I'm not sure exactly what you mean by holes.

**Comment by xsmeths** [comment]
![2021-01-13_12 50 35](https://user-images.githubusercontent.com/6798793/104454667-1d516780-559e-11eb-8b98-cf1737318488.png)
what it looked like before exploding multiple pieces of tnt together
![2021-01-13_12 51 10](https://user-images.githubusercontent.com/6798793/104454725-30fcce00-559e-11eb-9e93-1fc1096461b6.png)
what it looked like after thanks to the falling blocks before it was healed

**Comment by pmdevita** [comment]
Hmm that's odd, the plugin is supposed to hold gravity blocks in place during an explosion. I'll have to look into this.

**Comment by xsmeths** [comment]
> Hmm that's odd, the plugin is supposed to hold gravity blocks in place during an explosion. I'll have to look into this.

Alright, appreciate it, let me know how you get along, appreciate someone working on creeperheal again, i used the old one back in the day :)

**Comment by pmdevita** [comment]
Was the second TNT exploded in the crater of the first explosion?

**Comment by xsmeths** [comment]
I think so yes

**Comment by pmdevita** [comment]
Ah OK. It would seem that the first explosion is repairing over the second explosion before it finishes repairing and that is the problem you are describing. I'm going to close since issue #5 tracks explosion merging, which should be the solution to this. If you think something different is going on feel free to reopen
