### ISSUE TITLE
Custom explosions from plugins like Cannons

### ISSUE THREAD

**Issue by haegar123** [pmdevita/CreeperHeal2#4]
Hi
I already postet this on the disscussion thread on spigot. Could you add custom explosions like those from the Cannons Plugin? Now it just repairs vanilla explosions and those huge craters from the Cannons stay. I have seen this option on the predecessor plugin.

Thank you!

**Comment by pmdevita** [comment]
Looks like the original CreeperHeal plugin supported "custom" explosions, which I'm guessing were just explosions with an unknown or unidentifiable type. Blanket support for any custom explosion would be easiest but I'm going to experiment to see if users could define specific custom explosion types in the config

**Comment by pmdevita** [comment]
https://www.spigotmc.org/resources/cannons.56764/ https://github.com/DerPavlov/Cannons

**Comment by SmallSansSerif** [comment]
Let me echo the previous comment in asking for this type of explosion option. I also use Cannons.

> Looks like the original CreeperHeal plugin supported "custom" explosions, which I'm guessing were just explosions with an unknown or unidentifiable type. Blanket support for any custom explosion would be easiest but I'm going to experiment to see if users could define specific custom explosion types in the config

**Comment by PixelABPlus** [comment]
> Looks like the original CreeperHeal plugin supported "custom" explosions, which I'm guessing were just explosions with an unknown or unidentifiable type. Blanket support for any custom explosion would be easiest but I'm going to experiment to see if users could define specific custom explosion types in the config

How's it going

**Comment by pmdevita** [comment]
> > Looks like the original CreeperHeal plugin supported "custom" explosions, which I'm guessing were just explosions with an unknown or unidentifiable type. Blanket support for any custom explosion would be easiest but I'm going to experiment to see if users could define specific custom explosion types in the config
> 
> How's it going

https://github.com/pmdevita/CreeperHeal2/discussions/14

**Comment by PixelABPlus** [comment]
> > > Looks like the original CreeperHeal plugin supported "custom" explosions, which I'm guessing were just explosions with an unknown or unidentifiable type. Blanket support for any custom explosion would be easiest but I'm going to experiment to see if users could define specific custom explosion types in the config
> > 
> > 
> > How's it going
> 
> #14

CreeperHeal1 can fix most blocks includes the holes made by Cannons, but Creeperheal1 cannot fix the new block after Minecraft 1.11, I think maybe I can use both CreeperHeal1 and yours CreeperHeal2, to fix every block, just make sure your plugin only fix the new blocks

**Comment by pmdevita** [comment]
There is a system in place now for fixing compatibility with other plugins so this is next on my list after paintings

**Comment by pmdevita** [comment]
It's not really clear how the old plugin repairs Cannon damage, my best guess is through here

https://github.com/nitnelave/CreeperHeal/blob/afe4edbb5421ac6f744c5505a424acafd8fb547f/src/main/java/com/nitnelave/CreeperHeal/listeners/GriefListener.java#L14

or maybe we can listen to this event

https://github.com/DerPavlov/Cannons/blob/master/src/main/java/at/pavlov/cannons/event/ProjectilePiercingEvent.java

**Comment by pmdevita** [comment]
The solution was actually stupid simple and I can't believe I didn't realize it lol. It should be fixed in the next release.

If you use Cannons, please double check this for me, it's possible it is this simple but I might still be missing something. Open this issue again if it's still broken.
